export const CONNECT_IDENTITY_SUCCESS = 'CONNECT_IDENTITY_SUCCESS';
export const CONNECT_IDENTITY_STARTED = 'CONNECT_IDENTITY_STARTED';
export const CONNECT_IDENTITY_FAILURE = 'CONNECT_IDENTITY_FAILURE';

export const UPDATE_CLAIM = 'UPDATE_CLAIM';
export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION';
export const SET_SUBMITTING = 'SET_SUBMITTING';
