export const CONNECT_IDENTITY_SUCCESS = 'CONNECT_IDENTITY_SUCCESS';
export const CONNECT_IDENTITY_STARTED = 'CONNECT_IDENTITY_STARTED';
export const CONNECT_IDENTITY_FAILURE = 'CONNECT_IDENTITY_FAILURE';

export const REQUEST_CLAIM_SUCCESS = 'REQUEST_CLAIM_SUCCESS';
export const REQUEST_CLAIM_STARTED = 'REQUEST_CLAIM_STARTED';
export const REQUEST_CLAIM_FAILURE = 'REQUEST_CLAIM_FAILURE';
